### ISSUE TITLE
Use buffer instead of deprecated binary string

### ISSUE THREAD

**Issue by Verdier** [mathiasbynens/windows-1252#2]
Hi, thanks for your project! Do you think that it's possible to replace the use of binary string (which are deprecated in NodeJS 4) as input by a `Buffer`?

**Comment by mathiasbynens** [comment]
> binary string (which are deprecated in NodeJS 4)

Do you have a link with more info about this?

**Comment by Verdier** [comment]
Yes, to retrieve a binary string from a `Buffer`, you have to call `buffer.toString('binary')` but regarding the `Buffer` doc (https://nodejs.org/api/buffer.html) `Buffer#toString('binary')` is deprecated.
> 'binary' - A way of encoding raw binary data into strings by using only the first 8 bits of each character. This encoding method is deprecated and should be avoided in favor of Buffer objects where possible. This encoding will be removed in future versions of Node.js.

But your library needs a **binary encoded string** to work, why not directly a `buffer` instance?

**Comment by mathiasbynens** [comment]
Mainly because I wanted to have [wide browser/engine support](https://github.com/mathiasbynens/windows-1252#support) without requiring `Buffer` shims.

**Comment by Verdier** [comment]
That's definitely a very good reason...

Le sam. 24 oct. 2015 11:17, Mathias Bynens <notifications@github.com> a
écrit :

**Comment by mathiasbynens** [comment]
But you’re right — maybe these libraries should be updated to just deal with buffers / typed arrays instead. Those who need bitstring/browser support can still use the current version.

**Comment by piranna** [comment]
Any update on this?

**Comment by mathiasbynens** [comment]
Try v3.0.0 and let me know what you think!

**Comment by Prinzhorn** [comment]
I'm a little confused about the choice of `Uint16Array` (vs `Uint8Array`), I assume I must be missing something. Isn't windows-1252 single-byte? 

If I want to do anything with the result (e.g. write to a stream) I need to copy it to a `Uint8Array` and skip every second byte because otherwise I end up with every second byte being `0`. In other words, this library also uses twice the memory for no reason?

Can the higher bits ever be anything but 0? Here's what I'm currently doing:

```js
const encodedCSV16 = windows1252.encode(csv, {
  mode: 'replacement',
});

// Copy over the values (they will never be larger than 255 because single-byte encoding).
const encodedCSV = new Uint8Array(encodedCSV16.length);

for (let i = 0; i < encodedCSV16.length; i++) {
  encodedCSV[i] = encodedCSV16[i];
}
```

now I can pass `encodedCSV` to e.g. `stream.write()`.
